### ISSUE TITLE
Any plans for a "streaming" implementation?

### ISSUE THREAD

**Issue by dheijl** [yotarok/flacenc-rs#1]
This looks extremely promising.

My question: are there any plans for adding an API for FLAC encoding a never-ending stream (like an internet radio or a streaming service), with a callback based or pull based API for getting chunks of the FLAC encoded data of the input stream? 

Or would you consider adding such a feature?

I'm not sure that my Rust skills are sufficient to allow me to create a pull request myself (if you would consider adding such a feature).

**Comment by yotarok** [comment]
Hi, Thanks for the comment (and sorry for the late reply)

This crate can be used both as a library and a binary.
With linking this crate as a library, you can directly call internal encoding functions.
Therefore, one can easily develop streaming application by copy-pasting and adapting `encode_with_fixed_block_size` (https://github.com/yotarok/flacenc-rs/blob/main/src/coding.rs#L444).

What needed to be done in streaming encoder is basically:
1. prepare `FrameBuf` (https://github.com/yotarok/flacenc-rs/blob/main/src/source.rs#L46) with your partial input.
2. call `encode_fixed_size_frame`.
3. write frame to the output file, see https://github.com/yotarok/flacenc-rs/blob/main/src/main.rs#L83

**Comment by dheijl** [comment]
Thanks for the suggestion, I'll give it a go!

**Comment by dheijl** [comment]
Looking at the source code I don't think that it is that easy. 
There is no output file, only an endless HTTP output stream that consists of a single (dummy) FLAC MetaData block followed by the captured input PCM stream, encoded to FLAC as it arrives (captured from WASAPI or Alsa or Pulse or Jack). The delay between input and output should be as small as possible (a couple of seconds is acceptable). 
At least that is what I am trying to achieve, without knowing if it is actually possible...

**Comment by yotarok** [comment]
You can obtain what will be written in the output file as `BitVec` via `write` method of `BitRepr` (https://github.com/yotarok/flacenc-rs/blob/main/src/component.rs#L44).
Assuming that you have `frame` that is encoded by `encode_fixed_size_frame`, you can do like following:
```rust
let mut bv: BitVec<u8, Msb0> = BitVec::with_capacity(frame.count_bits());
frame.write(&mut bv).expect("Bitstream formatting failed.");
```
and then `bv.as_raw_slice(): &[u8]` can be passed to a socket, or other APIs.

**Comment by dheijl** [comment]
Yes, the best option seems to use the low-level API to implement my own version of Stream.
Thanks for your help!
