### ISSUE TITLE
Add simd library as a feature, support a stable simd crate

### ISSUE THREAD

**Issue by dtzxporter** [yotarok/flacenc-rs#58]
Would it be possible to break out the simd features so we can implement a rust stable compatible one?

I would be interested in doing some of this work if it would be accepted in the library... at this rate who knows when portable simd will be stabilized 😀

**Comment by dtzxporter** [comment]
Well, I didn't see the fakesimd change, never mind!

**Comment by yotarok** [comment]
Yes you can use "fakesimd" this is included since v0.2.0 crate that has been just released.
Honestly speaking, "fakesimd" feature isn't tested thoroughly.  So, please file a bug when you encountered to a bug.
