### ISSUE TITLE
PreloadedSignal::from_samples?

### ISSUE THREAD

**Issue by forslund** [yotarok/flacenc-rs#6]
This is probably a stupid question but what is the "correct" way to encode a set of samples? I record i16 from the mic and then want to encode them as flac before sending them off to a server.

I basically copied code `main.rs` and removed the test flag from `PreloadedSignal::from_samples` and used that instead of from_path, but it feels like there is a better(TM) way of doing it. A pointer in the right direction would be much appreciated.

**Comment by yotarok** [comment]
`PreloadedSignal::from_samples` is a straight forward way to do it when you have samples already in a buffer.
Probably, it's better to remove the test flag.

Another option is to define some structs satisfying `Source` trait.
This option might be useful when you want to write an adapter to another I/O library, or for dealing with streamed samples.

**Comment by forslund** [comment]
Yes, the from_samples was very convenient for my simple case. In the long run I might want to implement the Stream trait for some better performance.
